name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.X"
      - run: yarn
      - name: Test
        run: yarn test
      - run: yarn build:embeds
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "courier-components-xvdza5"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "./packages/embeddable/dist"
          DEST_DIR: "/test"
